version: '3'

services:
  spark:
    build: . #il va maintenant allez chercher le Dockerfile ici
    container_name: spark_container
    depends_on:
      - postgres
    networks:
      - sparknet

  postgres:
    image: postgres:latest
    container_name: postgres_container_full_data_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: full_data_db
    ports:
      - "5432:5432"
    networks:
      - sparknet

networks:
  sparknet:
    driver: bridge
